import Foundation

/// `AVAILABLE_SUBTITLE_LANGUAGES` from PlayerSettingsDataStore.kt, shared by the
/// audio and subtitle language pickers.
public enum SettingsLanguageCatalog {
    public static let availableLanguages: [NuvioSettingOption] = [
        NuvioSettingOption(id: "af", title: "Afrikaans"),
        NuvioSettingOption(id: "sq", title: "Albanian"),
        NuvioSettingOption(id: "am", title: "Amharic"),
        NuvioSettingOption(id: "ar", title: "Arabic"),
        NuvioSettingOption(id: "hy", title: "Armenian"),
        NuvioSettingOption(id: "az", title: "Azerbaijani"),
        NuvioSettingOption(id: "eu", title: "Basque"),
        NuvioSettingOption(id: "be", title: "Belarusian"),
        NuvioSettingOption(id: "bn", title: "Bengali"),
        NuvioSettingOption(id: "bs", title: "Bosnian"),
        NuvioSettingOption(id: "bg", title: "Bulgarian"),
        NuvioSettingOption(id: "my", title: "Burmese"),
        NuvioSettingOption(id: "ca", title: "Catalan"),
        NuvioSettingOption(id: "zh", title: "Chinese"),
        NuvioSettingOption(id: "zh-CN", title: "Chinese (Simplified)"),
        NuvioSettingOption(id: "zh-TW", title: "Chinese (Traditional)"),
        NuvioSettingOption(id: "hr", title: "Croatian"),
        NuvioSettingOption(id: "cs", title: "Czech"),
        NuvioSettingOption(id: "da", title: "Danish"),
        NuvioSettingOption(id: "nl", title: "Dutch"),
        NuvioSettingOption(id: "en", title: "English"),
        NuvioSettingOption(id: "et", title: "Estonian"),
        NuvioSettingOption(id: "tl", title: "Filipino"),
        NuvioSettingOption(id: "fi", title: "Finnish"),
        NuvioSettingOption(id: "fr", title: "French"),
        NuvioSettingOption(id: "gl", title: "Galician"),
        NuvioSettingOption(id: "ka", title: "Georgian"),
        NuvioSettingOption(id: "de", title: "German"),
        NuvioSettingOption(id: "el", title: "Greek"),
        NuvioSettingOption(id: "gu", title: "Gujarati"),
        NuvioSettingOption(id: "he", title: "Hebrew"),
        NuvioSettingOption(id: "hi", title: "Hindi"),
        NuvioSettingOption(id: "hu", title: "Hungarian"),
        NuvioSettingOption(id: "is", title: "Icelandic"),
        NuvioSettingOption(id: "id", title: "Indonesian"),
        NuvioSettingOption(id: "ga", title: "Irish"),
        NuvioSettingOption(id: "it", title: "Italian"),
        NuvioSettingOption(id: "ja", title: "Japanese"),
        NuvioSettingOption(id: "kn", title: "Kannada"),
        NuvioSettingOption(id: "kk", title: "Kazakh"),
        NuvioSettingOption(id: "km", title: "Khmer"),
        NuvioSettingOption(id: "ko", title: "Korean"),
        NuvioSettingOption(id: "lo", title: "Lao"),
        NuvioSettingOption(id: "lv", title: "Latvian"),
        NuvioSettingOption(id: "lt", title: "Lithuanian"),
        NuvioSettingOption(id: "mk", title: "Macedonian"),
        NuvioSettingOption(id: "ms", title: "Malay"),
        NuvioSettingOption(id: "ml", title: "Malayalam"),
        NuvioSettingOption(id: "mt", title: "Maltese"),
        NuvioSettingOption(id: "mr", title: "Marathi"),
        NuvioSettingOption(id: "mn", title: "Mongolian"),
        NuvioSettingOption(id: "ne", title: "Nepali"),
        NuvioSettingOption(id: "no", title: "Norwegian"),
        NuvioSettingOption(id: "pa", title: "Punjabi"),
        NuvioSettingOption(id: "fa", title: "Persian"),
        NuvioSettingOption(id: "pl", title: "Polish"),
        NuvioSettingOption(id: "pt", title: "Portuguese (Portugal)"),
        NuvioSettingOption(id: "pt-br", title: "Portuguese (Brazil)"),
        NuvioSettingOption(id: "ro", title: "Romanian"),
        NuvioSettingOption(id: "ru", title: "Russian"),
        NuvioSettingOption(id: "sr", title: "Serbian"),
        NuvioSettingOption(id: "si", title: "Sinhala"),
        NuvioSettingOption(id: "sk", title: "Slovak"),
        NuvioSettingOption(id: "sl", title: "Slovenian"),
        NuvioSettingOption(id: "es", title: "Spanish"),
        NuvioSettingOption(id: "es-419", title: "Spanish (Latin America)"),
        NuvioSettingOption(id: "sw", title: "Swahili"),
        NuvioSettingOption(id: "sv", title: "Swedish"),
        NuvioSettingOption(id: "ta", title: "Tamil"),
        NuvioSettingOption(id: "te", title: "Telugu"),
        NuvioSettingOption(id: "th", title: "Thai"),
        NuvioSettingOption(id: "tr", title: "Turkish"),
        NuvioSettingOption(id: "uk", title: "Ukrainian"),
        NuvioSettingOption(id: "ur", title: "Urdu"),
        NuvioSettingOption(id: "uz", title: "Uzbek"),
        NuvioSettingOption(id: "vi", title: "Vietnamese"),
        NuvioSettingOption(id: "cy", title: "Welsh"),
        NuvioSettingOption(id: "zu", title: "Zulu"),
    ]
}
